import pandas as pd


def build_executive_report(
    df,
    kpis=None,
    forecast_info=None,
    forecast_explanation=None,
    executive_insights=None
):
    """
    Build a structured executive report from
    the results already calculated by InsightIQ.
    """

    rows = df.shape[0]
    columns = df.shape[1]

    missing_values = int(
        df.isnull().sum().sum()
    )

    duplicate_rows = int(
        df.duplicated().sum()
    )

    numeric_columns = len(
        df.select_dtypes(
            include="number"
        ).columns
    )

    categorical_columns = len(
        df.select_dtypes(
            include=["object", "category"]
        ).columns
    )

    report = []

    report.append(
        "# 📊 InsightIQ Executive Report"
    )

    report.append(
        "## 📋 Dataset Overview"
    )

    report.append(
        f"- **Rows:** {rows:,}"
    )

    report.append(
        f"- **Columns:** {columns:,}"
    )

    report.append(
        f"- **Missing Values:** {missing_values:,}"
    )

    report.append(
        f"- **Duplicate Rows:** {duplicate_rows:,}"
    )

    report.append(
        f"- **Numeric Columns:** {numeric_columns:,}"
    )

    report.append(
        f"- **Categorical Columns:** {categorical_columns:,}"
    )

    # ---------------------------------------
    # Smart KPIs
    # ---------------------------------------

    if kpis:

        report.append(
            "## 📌 Smart KPIs"
        )

        for kpi in kpis:

            value = kpi.get(
                "value"
            )

            label = kpi.get(
                "label",
                kpi.get("column", "Metric")
            )

            if isinstance(
                value,
                (int, float)
            ):

                report.append(
                    f"- **{label}:** {value:,.2f}"
                )

            else:

                report.append(
                    f"- **{label}:** {value}"
                )

    # ---------------------------------------
    # Executive Insights
    # ---------------------------------------

    if executive_insights:

        report.append(
            "## ✨ Executive Insights"
        )

        report.append(
            executive_insights
        )

    # ---------------------------------------
    # Forecast
    # ---------------------------------------

    if forecast_info:

        report.append(
            "## 📈 Forecast"
        )

        report.append(
            f"- **Model:** "
            f"{forecast_info.get('model', 'Unknown')}"
        )

        report.append(
            f"- **Frequency:** "
            f"{forecast_info.get('frequency', 'Unknown')}"
        )

        report.append(
            f"- **Historical Observations:** "
            f"{forecast_info.get('observations', 'Unknown')}"
        )

        report.append(
            f"- **Forecast Periods:** "
            f"{forecast_info.get('forecast_periods', 'Unknown')}"
        )

        report.append(
            f"- **Projected Change:** "
            f"{forecast_info.get('change_percent', 0):.2f}%"
        )

        validation = forecast_info.get(
            "validation"
        )

        if validation:

            report.append(
                "### 🎯 Forecast Validation"
            )

            report.append(
                f"- **MAE:** "
                f"{validation.get('mae', 0):,.2f}"
            )

            report.append(
                f"- **RMSE:** "
                f"{validation.get('rmse', 0):,.2f}"
            )

            mape = validation.get(
                "mape"
            )

            if mape is not None:

                report.append(
                    f"- **MAPE:** "
                    f"{mape:.2f}%"
                )

    # ---------------------------------------
    # AI Forecast Explanation
    # ---------------------------------------

    if forecast_explanation:

        report.append(
            "## 🤖 AI Forecast Explanation"
        )

        report.append(
            forecast_explanation
        )

    # ---------------------------------------
    # Footer
    # ---------------------------------------

    report.append(
        "---"
    )

    report.append(
        "Generated by **InsightIQ**"
    )

    return "\n\n".join(report)