import streamlit as st

from utils.kpis import detect_kpis

from utils.report import build_executive_report

from utils.pdf_report import create_executive_pdf

from utils.ui import apply_insightiq_style


# ---------------------------------------
# Page Configuration
# ---------------------------------------

st.set_page_config(
    page_title="Executive Report",
    page_icon="📄",
    layout="wide"
)

apply_insightiq_style()


# ---------------------------------------
# Header
# ---------------------------------------

st.markdown(
    """
    <div style="
        padding: 1.5rem 1.8rem;
        border: 1px solid rgba(128,128,128,0.25);
        border-radius: 16px;
        margin-bottom: 1.5rem;
    ">

    <h1 style="margin-bottom: 0.3rem;">
        📄 InsightIQ Executive Report
    </h1>

    <p style="
        font-size: 1.1rem;
        margin-bottom: 0.3rem;
    ">
        One professional report from your complete analysis.
    </p>

    <p style="
        opacity: 0.7;
        margin-bottom: 0;
    ">
        Analyze → Forecast → Validate → Explain → Report
    </p>

    </div>
    """,
    unsafe_allow_html=True
)


# ---------------------------------------
# Dataset Check
# ---------------------------------------

if "data" not in st.session_state:

    st.warning(
        "⚠️ Please upload a dataset from the Dashboard first."
    )

    st.stop()


df = st.session_state["data"]


# ---------------------------------------
# Collect Results
# ---------------------------------------

kpis = detect_kpis(df)

forecast_info = st.session_state.get(
    "forecast_info"
)

forecast_explanation = st.session_state.get(
    "forecast_explanation"
)

executive_insights = st.session_state.get(
    "executive_report"
)

historical = st.session_state.get(
    "historical_forecast"
)

forecast = st.session_state.get(
    "forecast_data"
)

forecast_date_column = st.session_state.get(
    "forecast_date_column"
)

forecast_value_column = st.session_state.get(
    "forecast_value_column"
)


# ---------------------------------------
# Report Readiness
# ---------------------------------------

st.subheader(
    "📊 Report Readiness"
)

ready1, ready2, ready3, ready4 = st.columns(4)

with ready1:

    st.metric(
        "Dataset",
        "Ready"
    )

with ready2:

    st.metric(
        "KPIs",
        "Ready" if kpis else "Not available"
    )

with ready3:

    st.metric(
        "Forecast",
        "Ready" if forecast_info else "Not generated"
    )

with ready4:

    st.metric(
        "AI Analysis",
        "Ready"
        if (
            executive_insights
            or forecast_explanation
        )
        else "Not generated"
    )


st.divider()


# ---------------------------------------
# Generate Report
# ---------------------------------------

st.subheader(
    "📄 Generate Report"
)

st.caption(
    "The report uses the analysis already generated by InsightIQ."
)


if st.button(
    "📄 Generate Executive Report",
    use_container_width=True,
    key="generate_executive_report"
):

    report = build_executive_report(
        df=df,
        kpis=kpis,
        forecast_info=forecast_info,
        forecast_explanation=forecast_explanation,
        executive_insights=executive_insights
    )

    st.session_state[
        "final_executive_report"
    ] = report

    st.success(
        "✅ Executive report generated successfully!"
    )


# ---------------------------------------
# Display Markdown Report
# ---------------------------------------

if "final_executive_report" in st.session_state:

    st.divider()

    st.subheader(
        "📋 Report Preview"
    )

    st.markdown(
        st.session_state[
            "final_executive_report"
        ]
    )

    st.download_button(
        label="⬇️ Download Markdown Report",
        data=st.session_state[
            "final_executive_report"
        ],
        file_name="InsightIQ_Executive_Report.md",
        mime="text/markdown",
        use_container_width=True,
        key="download_markdown_report"
    )


# ---------------------------------------
# Generate PDF
# ---------------------------------------

st.divider()

st.subheader(
    "📕 Professional PDF Report"
)

st.caption(
    "Includes dataset summary, KPIs, AI insights, "
    "forecast chart and validation metrics."
)


if st.button(
    "📕 Generate PDF Report",
    use_container_width=True,
    key="generate_pdf_report"
):

    with st.spinner(
        "Creating your professional PDF..."
    ):

        try:

            pdf_bytes = create_executive_pdf(
                df=df,
                kpis=kpis,
                executive_insights=executive_insights,
                forecast_info=forecast_info,
                forecast_explanation=forecast_explanation,
                historical=historical,
                forecast=forecast,
                forecast_date_column=forecast_date_column,
                forecast_value_column=forecast_value_column,
            )

            st.session_state[
                "executive_pdf"
            ] = pdf_bytes

            st.success(
                "✅ PDF report generated successfully!"
            )

        except Exception as e:

            st.error(
                f"❌ PDF generation failed: {e}"
            )


# ---------------------------------------
# Download PDF
# ---------------------------------------

if "executive_pdf" in st.session_state:

    st.download_button(
        label="⬇️ Download Professional PDF",
        data=st.session_state[
            "executive_pdf"
        ],
        file_name="InsightIQ_Executive_Report.pdf",
        mime="application/pdf",
        use_container_width=True,
        key="download_pdf_report"
    )


# ---------------------------------------
# Footer
# ---------------------------------------

st.divider()

st.caption(
    "Powered by InsightIQ • Groq • LangChain • Streamlit"
)